created the left column text
Zyanvel/sign-up-form pull request #5
Opened 2022-06-10 03:40 UTC by PemaYT

left text has been inputted

2022-06-10 06:07 UTC, Zyanvel commented on index.html
> +            <h1>Learn to code by<br>
Hi! I would suggest to change the code like this:
```suggestion
            <h1>Learn to code by<br>watching others </h1>
```

2022-06-10 06:09 UTC, Zyanvel commented on styles.css
> +    /* height: 800px; */
Nit: If you are not using this, could you please remove it?

2022-06-10 06:09 UTC, Zyanvel commented on styles.css
> +        /* height: 1000px; */
Nit: If you are not using this, could you please remove it?

2022-06-10 06:10 UTC, Zyanvel commented on styles.css
> +    /* display: flex; */
Nit: Could you please remove the extra code?

2022-06-10 06:10 UTC, Zyanvel commented on styles.css
> +    /* padding: 5% 10% 5% 10%; */
Same here ☝️

2022-06-10 06:11 UTC, Zyanvel requested changes
Overall looks great! Just left some nit comments since this will help you to write cleaner code 😄 Let me know if you have any questions

2022-06-10 21:13 UTC, Zyanvel approved these changes
Looks good to me :)

2022-06-11 01:19 UTC, soleyingunn approved these changes
Looks good to me

2022-06-12 06:36 UTC, merged