Contact form
Zyanvel/sign-up-form pull request #7
Opened 2022-07-22 19:48 UTC by PemaYT

sign up form - not 100% sure about mobile compatibility, please check :)

2022-07-23 06:31 UTC, Zyanvel commented on styles.css
> +    color: red;
Nit: I would advice to use a color picker and select the color from the design :) just for practice

2022-07-23 07:27 UTC, Zyanvel requested changes
Nice job! Left one nit comment and it's just matter to review the width for the mobile screen.

2022-07-26 04:55 UTC, Zyanvel approved these changes

2022-07-26 05:04 UTC, PemaYT commented
one more ticket left hehe

2022-07-26 06:00 UTC, soleyingunn commented
How can I open the code to review it?

On Mon, Jul 25, 2022 at 7:04 PM PemaYT ***@***.***> wrote:

> Closed #7 <https://github.com/Zyanvel/sign-up-form/pull/7>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Zyanvel/sign-up-form/pull/7#event-7061646296>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW7NWFLELGOTP4BTEKICE73VV5WV7ANCNFSM54MS27AA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-26 06:03 UTC, soleyingunn commented
In my VS Code so I can inspect it I mean :) Sorry didn't mean to be unclear

On Mon, Jul 25, 2022 at 8:00 PM Sóley Ingunn Svanbergsdóttir <
***@***.***> wrote:

> How can I open the code to review it?
>
> On Mon, Jul 25, 2022 at 7:04 PM PemaYT ***@***.***> wrote:
>
>> Closed #7 <https://github.com/Zyanvel/sign-up-form/pull/7>.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Zyanvel/sign-up-form/pull/7#event-7061646296>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AW7NWFLELGOTP4BTEKICE73VV5WV7ANCNFSM54MS27AA>
>> .
>> You are receiving this because your review was requested.Message ID:
>> ***@***.***>
>>
>

2022-07-27 04:25 UTC, PemaYT commented
sorry hahaha my bad

2022-07-27 04:26 UTC, merged